// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package elevator.rmi.impl;

public final class ScalesImpl_Stub
    extends java.rmi.server.RemoteStub
    implements elevator.rmi.Scales, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getScalePosition_0;
    private static java.lang.reflect.Method $method_getScalePosition_1;
    private static java.lang.reflect.Method $method_getScalePosition_2;
    private static java.lang.reflect.Method $method_setScalePosition_3;
    private static java.lang.reflect.Method $method_setScalePosition_4;
    private static java.lang.reflect.Method $method_setScalePosition_5;
    private static java.lang.reflect.Method $method_setScalePosition_6;
    private static java.lang.reflect.Method $method_setScalePosition_7;
    
    static {
	try {
	    $method_getScalePosition_0 = elevator.rmi.Scales.class.getMethod("getScalePosition", new java.lang.Class[] {});
	    $method_getScalePosition_1 = elevator.rmi.Scales.class.getMethod("getScalePosition", new java.lang.Class[] {int.class});
	    $method_getScalePosition_2 = elevator.rmi.Scales.class.getMethod("getScalePosition", new java.lang.Class[] {int[].class});
	    $method_setScalePosition_3 = elevator.rmi.Scales.class.getMethod("setScalePosition", new java.lang.Class[] {int.class});
	    $method_setScalePosition_4 = elevator.rmi.Scales.class.getMethod("setScalePosition", new java.lang.Class[] {int.class, int.class});
	    $method_setScalePosition_5 = elevator.rmi.Scales.class.getMethod("setScalePosition", new java.lang.Class[] {int[].class});
	    $method_setScalePosition_6 = elevator.rmi.Scales.class.getMethod("setScalePosition", new java.lang.Class[] {int[].class, int.class});
	    $method_setScalePosition_7 = elevator.rmi.Scales.class.getMethod("setScalePosition", new java.lang.Class[] {int[].class, int[].class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ScalesImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getScalePosition()
    public int[] getScalePosition()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getScalePosition_0, null, -8601261060596936590L);
	    return ((int[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getScalePosition(int)
    public int getScalePosition(int $param_int_1)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getScalePosition_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 4119658312077355259L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getScalePosition(int[])
    public int[] getScalePosition(int[] $param_arrayOf_int_1)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getScalePosition_2, new java.lang.Object[] {$param_arrayOf_int_1}, -2209979704310766329L);
	    return ((int[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setScalePosition(int)
    public void setScalePosition(int $param_int_1)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setScalePosition_3, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -8288169480124495633L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setScalePosition(int, int)
    public void setScalePosition(int $param_int_1, int $param_int_2)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setScalePosition_4, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2)}, -421879673140593336L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setScalePosition(int[])
    public void setScalePosition(int[] $param_arrayOf_int_1)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setScalePosition_5, new java.lang.Object[] {$param_arrayOf_int_1}, 8938184755081819676L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setScalePosition(int[], int)
    public void setScalePosition(int[] $param_arrayOf_int_1, int $param_int_2)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setScalePosition_6, new java.lang.Object[] {$param_arrayOf_int_1, new java.lang.Integer($param_int_2)}, -4485527207079797719L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setScalePosition(int[], int[])
    public void setScalePosition(int[] $param_arrayOf_int_1, int[] $param_arrayOf_int_2)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setScalePosition_7, new java.lang.Object[] {$param_arrayOf_int_1, $param_arrayOf_int_2}, 1167890243389149752L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
