// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package elevator.rmi.impl;

public final class ScaleImpl_Stub
    extends java.rmi.server.RemoteStub
    implements elevator.rmi.Scale, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getScalePosition_0;
    private static java.lang.reflect.Method $method_setScalePosition_1;
    
    static {
	try {
	    $method_getScalePosition_0 = elevator.rmi.Scale.class.getMethod("getScalePosition", new java.lang.Class[] {});
	    $method_setScalePosition_1 = elevator.rmi.Scale.class.getMethod("setScalePosition", new java.lang.Class[] {int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ScaleImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getScalePosition()
    public int getScalePosition()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getScalePosition_0, null, 8726499427918184266L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setScalePosition(int)
    public void setScalePosition(int $param_int_1)
	throws elevator.rmi.IllegalParamException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setScalePosition_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -8288169480124495633L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
